runtime: python311  # Update based on your Python version

entrypoint: uvicorn main:app --host 0.0.0.0 --port $PORT

instance_class: F1  # Choose an instance class based on your needs

automatic_scaling:
  min_instances: 0
  max_instances: 1

handlers:
  - url: /.*
    script: auto
    secure: always
